"""empty message

Revision ID: 5b253a5b8013
Revises: 
Create Date: 2024-04-01 16:44:01.645016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b253a5b8013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('note_text', sa.String(length=500), nullable=True),
    sa.Column('note_timestamp', sa.String(length=10), nullable=True),
    sa.Column('video', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('edit_date', postgresql.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('video_src', sa.String(length=500), nullable=True),
    sa.Column('video_title', sa.String(length=200), nullable=True),
    sa.Column('video_length', sa.String(length=10), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('edit_date', postgresql.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('note')
    # ### end Alembic commands ###
